name: "test action hello"
author: "Christian Portilla Pauca"
description: "Imprime un mensaje"
inputs:
	input_text:
		description: "Mensaje"
		required: true 
outputs:
	output_text:
		description: "Output"
runs:
  using: node12
  main: main.js